# Meta Data for SEO
title: "Gatling documentation"
titleSeparator: "-"
description: "Gatling documentation"

## Open Graph + Twitter Cards
images: ["images/og-gatling.png"]
twitterSite: "GatlingTool"
twitterCreator: "GatlingTool"
facebookAuthor: "GatlingTool"
facebookPublisher: "GatlingTool"
ogLocale: "en_US"

# Header
logos:
  white: "images/logo-gatling.svg"
  black: "images/logo-gatling-noir.svg"

## JSON-LD
schemaName: "Gatling Corp"
schemaLogo: "images/og-gatling.png"
schemaTwitter: "https://twitter.com/GatlingTool"
schemaLinkedIn: "https://www.linkedin.com/company/gatling/"
schemaGitHub: https://github.com/gatling
schemaSection: tutorials

## Sitelinks Search Box
siteLinksSearchBox: false

## Chrome Browser
themeColor: "#fff"

# Images
quality: 85
bgColor: "#fff"
lqipWidth: "20x"

# Alert
alert: false
alertText: ""

# Edit Page
editPage: true

languages:
  default: java
  labels:
    - java: Java
    - ts: JavaScript
    - kt: Kotlin
    - scala: Scala

analytics:
  globalTrackingId: "G-MX12C3G05Y"
  tagManagerTrackingId: "GTM-TRJ26ZX"

docSearch:
  appId: "6PCIB797P6"
  apiKey: "e53c31a608bc353fc4c4a3694438886f"
  indexName: "gatling"
