services:
  hugo:
    image: floryn90/hugo:0.123.1-ext-alpine
    ports:
     - 1313:1313
    volumes:
     - .:/src
     - /src/content
     - /src/resources
     - /src/node_modules
    working_dir: /src
    environment:
      - DOCKER=true
    entrypoint: /src/bin/entrypoint.sh
